object Modules {
    const val app = ":app"
    const val common = ":core:common"
    const val ui = ":core:ui"
    const val designsystem = ":core:designsystem"
    const val network = ":core:network"
    const val database = ":core:database"
    const val datastore = ":core:datastore"
    const val data = ":core:data"
    const val domain = ":core:domain"
    const val auth_presentation = ":features:auth:auth_presentation"
    const val auth_data = ":features:auth:auth_data"
    const val auth_domain = ":features:auth:auth_domain"
    const val report_domain = ":features:report:report_domain"
    const val report_presentation = ":features:report:report_presentation"
    const val report_data = ":features:report:report_data"
    const val notification_presentation = ":features:notification:notification_presentation"
    const val profile_presentation = ":features:profile:profile_presentation"
    const val profile_data = ":features:profile:profile_data"
    const val profile_domain = ":features:profile:profile_domain"
    const val onboardings_presentation = ":features:onboardings:onboardings_presentation"
    const val settings_presentation = ":features:settings:settings_presentation"
    const val settings_domain = ":features:settings:settings_domain"
    const val settings_data = ":features:settings:settings_data"

    const val news_data = ":features:news:news_data"
    const val news_domain = ":features:news:news_domain"
    const val news_presentation = ":features:news:news_presentation"
}